=== checkpoint20/net-simulator/src/main/resources/dtd/netsimulator.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : net-simulator.dtd
    Created on : 14 May, 2006
    Author     : maks
-->

<!ELEMENT project ((routerShape* | desktopShape* | hubShape* | switchShape*)*, patchcord*)>
<!ATTLIST project 
    author      CDATA #IMPLIED
    description CDATA #IMPLIED
    createDate  CDATA #IMPLIED
    currentId   CDATA #REQUIRED>
    
    
<!ELEMENT routerShape (IP4Router?, socketShape+)>    
<!ATTLIST routerShape 
    id          CDATA #REQUIRED
    name        CDATA #REQUIRED
    description CDATA #IMPLIED
    x           CDATA #REQUIRED
    y           CDATA #REQUIRED>


<!ELEMENT desktopShape (IP4Router?, socketShape+)>    
<!ATTLIST desktopShape 
    id          CDATA #REQUIRED
    name        CDATA #REQUIRED
    description CDATA #IMPLIED
    x           CDATA #REQUIRED
    y           CDATA #REQUIRED>


<!ELEMENT hubShape (hub?, socketShape+)>    
<!ATTLIST hubShape 
    id          CDATA #REQUIRED
    name        CDATA #REQUIRED
    description CDATA #IMPLIED
    x           CDATA #REQUIRED
    y           CDATA #REQUIRED>

    
<!ELEMENT hub (port+)>
<!ATTLIST hub
    id          CDATA #REQUIRED>

    
<!ELEMENT switchShape (switch?, socketShape+)>    
<!ATTLIST switchShape 
    id          CDATA #REQUIRED
    name        CDATA #REQUIRED
    description CDATA #IMPLIED
    x           CDATA #REQUIRED
    y           CDATA #REQUIRED>

    
<!ELEMENT switch (port+)>
<!ATTLIST switch
    id          CDATA #REQUIRED>    
    

<!ELEMENT port EMPTY>
<!ATTLIST port
    id          CDATA #REQUIRED>
    
                        
<!ELEMENT IP4Router (eth+, routingTable?)>
<!ATTLIST IP4Router 
    id          CDATA #REQUIRED>
    

<!ELEMENT eth EMPTY>
<!ATTLIST eth 
    id          CDATA #REQUIRED
    name        CDATA #REQUIRED
    status      (0|1) #REQUIRED
    mac         CDATA #REQUIRED
    ip4         CDATA #IMPLIED
    ip4bcast    CDATA #IMPLIED
    ip4mask     CDATA #IMPLIED
    bandwidth   CDATA #IMPLIED>
    
<!ELEMENT routingTable (row*)>
    
<!ELEMENT row EMPTY>
<!ATTLIST row 
    target      CDATA #REQUIRED
    netmask     CDATA #REQUIRED
    gateway     CDATA #IMPLIED
    metric      CDATA #REQUIRED
    iface       CDATA #REQUIRED>

<!ELEMENT socketShape EMPTY>
<!ATTLIST socketShape
    id          CDATA #REQUIRED
    x           CDATA #REQUIRED
    y           CDATA #REQUIRED
    devId       CDATA #REQUIRED>
    
    
<!ELEMENT patchcord (media+, plug*)>    
<!ATTLIST patchcord
    id          CDATA #REQUIRED>
    
<!ELEMENT plug EMPTY>
<!ATTLIST plug
    id          CDATA #REQUIRED
    point       CDATA #REQUIRED
    x           CDATA #REQUIRED
    y           CDATA #REQUIRED
    socket      CDATA #IMPLIED>

<!ELEMENT media EMPTY>
<!ATTLIST media
    id          CDATA #REQUIRED
    pointsCount CDATA #REQUIRED>

=== checkpoint20/net-simulator/xml/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project PUBLIC "NET-Simulator/dtd/netsimulator.dtd" "http://www.net-simulator.org/dtd/1.0/netsimulator.dtd">
<project author="Maxim Tereshin" description="An example of the NET-Simulator virtual network" createDate="" currentId="711">
	<routerShape id="187" name="Router 0" description="" x="278" y="182">
		<IP4Router id="188">
			<eth id="190" name="eth0" status="1" mac="0:0:0:0:BC:0" ip4="10.0.0.11" ip4bcast="10.255.255.255" ip4mask="255.0.0.0" bandwidth="0" />
			<eth id="191" name="eth1" status="0" mac="0:0:0:0:BC:1" ip4="" ip4bcast="" ip4mask="" bandwidth="0" />
			<eth id="192" name="eth2" status="0" mac="0:0:0:0:BC:2" ip4="" ip4bcast="" ip4mask="" bandwidth="0" />
			<eth id="193" name="eth3" status="0" mac="0:0:0:0:BC:3" ip4="" ip4bcast="" ip4mask="" bandwidth="0" />
			<eth id="194" name="eth4" status="1" mac="0:0:0:0:BC:4" ip4="12.0.0.1" ip4bcast="12.0.0.255" ip4mask="255.255.255.0" bandwidth="0" />
			<eth id="195" name="eth5" status="0" mac="0:0:0:0:BC:5" ip4="" ip4bcast="" ip4mask="" bandwidth="0" />
			<eth id="196" name="eth6" status="0" mac="0:0:0:0:BC:6" ip4="" ip4bcast="" ip4mask="" bandwidth="0" />
			<eth id="197" name="eth7" status="1" mac="0:0:0:0:BC:7" ip4="11.0.0.11" ip4bcast="11.255.255.255" ip4mask="255.0.0.0" bandwidth="0" />
			<routingTable>
				<row target="12.0.0.0" netmask="255.255.255.0" gateway="" metric="1" iface="eth4" />
				<row target="10.0.0.0" netmask="255.0.0.0" gateway="" metric="1" iface="eth0" />
			</routingTable>
		</IP4Router>
		<socketShape id="198" x="308" y="200" devId="190" />
		<socketShape id="199" x="316" y="200" devId="191" />
		<socketShape id="200" x="324" y="200" devId="192" />
		<socketShape id="201" x="332" y="200" devId="193" />
		<socketShape id="202" x="340" y="200" devId="194" />
		<socketShape id="203" x="348" y="200" devId="195" />
		<socketShape id="204" x="356" y="200" devId="196" />
		<socketShape id="205" x="364" y="200" devId="197" />
	</routerShape>
	<desktopShape id="206" name="Компьютер 1" description="" x="132" y="241">
		<IP4Router id="207">
			<eth id="209" name="eth0" status="1" mac="0:0:0:0:CF:0" ip4="10.0.0.10" ip4bcast="10.255.255.255" ip4mask="255.0.0.0" bandwidth="0" />
			<routingTable>
				<row target="12.0.0.0" netmask="255.255.255.0" gateway="10.0.0.11" metric="0" iface="eth0" />
				<row target="10.0.0.0" netmask="255.0.0.0" gateway="" metric="0" iface="eth0" />
				<row target="11.0.0.0" netmask="255.0.0.0" gateway="10.0.0.11" metric="0" iface="eth0" />
			</routingTable>
		</IP4Router>
		<socketShape id="210" x="170" y="276" devId="209" />
	</desktopShape>
	<desktopShape id="211" name="Компьютер 2" description="" x="498" y="283">
		<IP4Router id="212">
			<eth id="214" name="eth0" status="1" mac="0:0:0:0:D4:0" ip4="11.0.0.10" ip4bcast="11.255.255.255" ip4mask="255.0.0.0" bandwidth="0" />
			<routingTable>
				<row target="11.0.0.0" netmask="255.0.0.0" gateway="" metric="1" iface="eth0" />
				<row target="12.0.0.0" netmask="255.0.0.0" gateway="11.0.0.11" metric="0" iface="eth0" />
			</routingTable>
		</IP4Router>
		<socketShape id="215" x="536" y="318" devId="214" />
	</desktopShape>
	<switchShape id="230" name="Switch 3" description="" x="327" y="106">
		<switch id="231">
			<port id="232" />
			<port id="233" />
			<port id="234" />
			<port id="235" />
			<port id="236" />
			<port id="237" />
			<port id="238" />
			<port id="239" />
		</switch>
		<socketShape id="240" x="357" y="124" devId="232" />
		<socketShape id="241" x="365" y="124" devId="233" />
		<socketShape id="242" x="373" y="124" devId="234" />
		<socketShape id="243" x="381" y="124" devId="235" />
		<socketShape id="244" x="389" y="124" devId="236" />
		<socketShape id="245" x="397" y="124" devId="237" />
		<socketShape id="246" x="405" y="124" devId="238" />
		<socketShape id="247" x="413" y="124" devId="239" />
	</switchShape>
	<desktopShape id="248" name="Компьютер 4" description="" x="229" y="30">
		<IP4Router id="249">
			<eth id="251" name="eth0" status="1" mac="0:0:0:0:F9:0" ip4="12.0.0.10" ip4bcast="12.0.0.255" ip4mask="255.255.255.0" bandwidth="0" />
			<routingTable>
				<row target="12.0.0.0" netmask="255.255.255.0" gateway="" metric="1" iface="eth0" />
				<row target="10.0.0.0" netmask="255.0.0.0" gateway="12.0.0.1" metric="0" iface="eth0" />
			</routingTable>
		</IP4Router>
		<socketShape id="252" x="267" y="65" devId="251" />
	</desktopShape>
	<desktopShape id="253" name="Компьютер 5" description="" x="680" y="0">
		<IP4Router id="254">
			<eth id="256" name="eth0" status="1" mac="0:0:0:0:FE:0" ip4="12.0.0.11" ip4bcast="12.0.0.255" ip4mask="255.255.255.0" bandwidth="0" />
			<routingTable>
				<row target="12.0.0.0" netmask="255.255.255.0" gateway="" metric="1" iface="eth0" />
				<row target="0.0.0.0" netmask="0.0.0.0" gateway="12.0.0.1" metric="0" iface="eth0" />
			</routingTable>
		</IP4Router>
		<socketShape id="257" x="718" y="35" devId="256" />
	</desktopShape>
	<switchShape id="625" name="Switch 6" description="" x="512" y="96">
		<switch id="626">
			<port id="627" />
			<port id="628" />
			<port id="629" />
			<port id="630" />
			<port id="631" />
			<port id="632" />
			<port id="633" />
			<port id="634" />
		</switch>
		<socketShape id="635" x="542" y="114" devId="627" />
		<socketShape id="636" x="550" y="114" devId="628" />
		<socketShape id="637" x="558" y="114" devId="629" />
		<socketShape id="638" x="566" y="114" devId="630" />
		<socketShape id="639" x="574" y="114" devId="631" />
		<socketShape id="640" x="582" y="114" devId="632" />
		<socketShape id="641" x="590" y="114" devId="633" />
		<socketShape id="642" x="598" y="114" devId="634" />
	</switchShape>
	<switchShape id="647" name="Switch 7" description="" x="662" y="188">
		<switch id="648">
			<port id="649" />
			<port id="650" />
			<port id="651" />
			<port id="652" />
			<port id="653" />
			<port id="654" />
			<port id="655" />
			<port id="656" />
		</switch>
		<socketShape id="657" x="692" y="206" devId="649" />
		<socketShape id="658" x="700" y="206" devId="650" />
		<socketShape id="659" x="708" y="206" devId="651" />
		<socketShape id="660" x="716" y="206" devId="652" />
		<socketShape id="661" x="724" y="206" devId="653" />
		<socketShape id="662" x="732" y="206" devId="654" />
		<socketShape id="663" x="740" y="206" devId="655" />
		<socketShape id="664" x="748" y="206" devId="656" />
	</switchShape>
	<switchShape id="674" name="Switch 8" description="" x="616" y="307">
		<switch id="675">
			<port id="676" />
			<port id="677" />
			<port id="678" />
			<port id="679" />
			<port id="680" />
			<port id="681" />
			<port id="682" />
			<port id="683" />
		</switch>
		<socketShape id="684" x="646" y="325" devId="676" />
		<socketShape id="685" x="654" y="325" devId="677" />
		<socketShape id="686" x="662" y="325" devId="678" />
		<socketShape id="687" x="670" y="325" devId="679" />
		<socketShape id="688" x="678" y="325" devId="680" />
		<socketShape id="689" x="686" y="325" devId="681" />
		<socketShape id="690" x="694" y="325" devId="682" />
		<socketShape id="691" x="702" y="325" devId="683" />
	</switchShape>
	<patchcord id="216">
		<media id="217" pointsCount="2" />
		<plug id="218" point="1" x="170" y="276" socket="210" />
		<plug id="219" point="2" x="308" y="200" socket="198" />
	</patchcord>
	<patchcord id="220">
		<media id="221" pointsCount="2" />
		<plug id="222" point="1" x="364" y="200" socket="205" />
		<plug id="223" point="2" x="536" y="318" socket="215" />
	</patchcord>
	<patchcord id="258">
		<media id="259" pointsCount="2" />
		<plug id="260" point="1" x="267" y="65" socket="252" />
		<plug id="261" point="2" x="357" y="124" socket="240" />
	</patchcord>
	<patchcord id="262">
		<media id="263" pointsCount="2" />
		<plug id="264" point="1" x="598" y="114" socket="642" />
		<plug id="265" point="2" x="718" y="35" socket="257" />
	</patchcord>
	<patchcord id="266">
		<media id="267" pointsCount="2" />
		<plug id="268" point="1" x="381" y="124" socket="243" />
		<plug id="269" point="2" x="340" y="200" socket="202" />
	</patchcord>
	<patchcord id="643">
		<media id="644" pointsCount="2" />
		<plug id="645" point="1" x="542" y="114" socket="635" />
		<plug id="646" point="2" x="413" y="124" socket="247" />
	</patchcord>
	<patchcord id="665">
		<media id="666" pointsCount="2" />
		<plug id="667" point="1" x="566" y="114" socket="638" />
		<plug id="668" point="2" x="716" y="206" socket="660" />
	</patchcord>
	<patchcord id="692">
		<media id="693" pointsCount="2" />
		<plug id="694" point="1" x="558" y="114" socket="637" />
		<plug id="695" point="2" x="654" y="325" socket="685" />
	</patchcord>
</project>
