=== checkpoint20/net-simulator/public_html/dtd/1.0/config.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : config.dtd
    Created on : 8 July, 2006
    Author     : maks
    Version    : 1.0
-->

<!ELEMENT config 
( whatOpenAfterStart? | background? | debug? | lastProject? | skins? | currentSkin?)*>


<!ELEMENT whatOpenAfterStart EMPTY>
<!ATTLIST whatOpenAfterStart
    value (lastProject | emptyProject | nothing) #REQUIRED>
    
    
<!ELEMENT lastProject EMPTY>
<!ATTLIST lastProject
    value CDATA #REQUIRED>
    
        
<!ELEMENT background EMPTY>
<!ATTLIST background
    value CDATA #REQUIRED>
    

<!ELEMENT debug (logger*)>


<!ELEMENT logger EMPTY>
<!ATTLIST logger
    name        CDATA #REQUIRED
    logLevel    (OFF|SEVERE|WARNING|INFO|CONFIG|FINE|FINER|FINEST|ALL) #REQUIRED>
        

<!ELEMENT skins (skin*)>
    
       
<!ELEMENT skin (shape*)>
<!ATTLIST skin
    name CDATA #REQUIRED>

    
<!ELEMENT shape EMPTY>
<!ATTLIST shape
    name (router|desktop|hub|switch) #REQUIRED
    socketsX CDATA #REQUIRED
    socketsY CDATA #REQUIRED
    socketsStep CDATA #REQUIRED>

    
<!ELEMENT currentSkin EMPTY>
<!ATTLIST currentSkin
    name CDATA #REQUIRED>

=== checkpoint20/net-simulator/cfg/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "NET-Simulator/dtd/config.dtd" "http://www.net-simulator.org/dtd/1.0/config.dtd">
<config>
	<whatOpenAfterStart value="lastProject" />
	<lastProject value="xml/test.xml" />
	<currentSkin name="basic" />
	<background value="#ffffff" />
	<skins>
		<skin name="basic">
			<shape name="router" socketsX="30" socketsY="18" socketsStep="8" />
			<shape name="desktop" socketsX="38" socketsY="35" socketsStep="0" />
			<shape name="hub" socketsX="30" socketsY="18" socketsStep="8" />
			<shape name="switch" socketsX="30" socketsY="18" socketsStep="8" />
		</skin>
	</skins>
	<debug>
		<logger name="org.netsimulator.term.RouteCLICommand" logLevel="INFO" />
		<logger name="org.netsimulator.term.IfconfigCLICommand" logLevel="ALL" />
		<logger name="org.netsimulator.term.PingCLICommand" logLevel="INFO" />
		<logger name="org.netsimulator.term.Terminal" logLevel="INFO" />
		<logger name="org.netsimulator.net.RoutingTable" logLevel="ALL" />
		<logger name="org.netsimulator.net.Media" logLevel="INFO" />
		<logger name="org.netsimulator.net.IP4Router" logLevel="INFO" />
		<logger name="org.netsimulator.net.RoutingTableRow" logLevel="ALL" />
		<logger name="org.netsimulator.net.ICMPEchoPacket" logLevel="INFO" />
		<logger name="org.netsimulator.net.EthernetInterface" logLevel="FINE" />
		<logger name="org.netsimulator.net.MACAddressesTable" logLevel="INFO" />
		<logger name="org.netsimulator.net.Switch" logLevel="INFO" />
		<logger name="org.netsimulator.gui.MainFrame" logLevel="INFO" />
	</debug>
</config>
